# Sanitized reference copy. See legacy_reference/README.md. Not used by the GUI.
library(readxl)
library(MASS)
library(stats)
library(utils)
library(base)
library(gdata)
# Run from a folder containing your input workbook; no personal working directory is stored here.

### Important!!!
ttn<-15  # Remember to change sheetcounts to the number of total sheets!!!

s=1;
finaldatatable<-data.frame(matrix(vector(),0,(2*ttn)));
pb = txtProgressBar(min = 0, max = ttn, initial = 0, style=3); 
for (s in 1:ttn){
  df<-read_excel("sample_workbook.xlsx",skip=6,sheet = s)
  # PRIVACY EDIT: original experiment-specific ranges are omitted.
  # Synthetic example for mass 100 at +/-5 ppm, formatted to 4 decimals.
  # Replace this example with expressions generated by format.py for your background.
  boolean <- ((df$m.z > 99.9995 & df$m.z < 100.0005))
  # Filter initial dataframe
  df <- df[!boolean, ]
  
  # Calculate total intensity with NA handling
  Intensitysum <- sum(df$Intensity, na.rm = TRUE)
  if(Intensitysum == 0) stop("Total intensity sum is zero - cannot normalize")
  
  # Identify valid rows in one operation
  valid_rows <- !is.na(df$Intensity) & df$Intensity >= 3000
  
  # Create results directly (no loops needed)
  Newdatatable <- data.frame(
    m_z = df$m.z[valid_rows],
    NormIntensity = (df$Intensity[valid_rows] / Intensitysum) * 100000,
    stringsAsFactors = FALSE
  )
  
  
  
  
  
  n<-length(Newdatatable$m_z)
  for (i in 1:n){
    finaldatatable[i,(2*s-1)]<-Newdatatable[i,1]
    finaldatatable[i,(2*s)]<-Newdatatable[i,2]
  }
  setTxtProgressBar(pb,s)
}
headers1=rep(1:ttn,each=2)
headers2=rep(c("mass","abund"),ttn)
finaldatatable<-rbind(headers1,headers2,finaldatatable)

# output
write.table(finaldatatable, file="legacy_results.csv",row.names=FALSE, col.names=FALSE, sep=",")



